[package]
name = "docx_readonly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.4"
quick-xml = "0.27.1"
walkdir = "2.3.2"